server:
  port: 8080
  servlet:
    context-path: /
spring:
#  devtools:
#    restart:
#      exclude: static/**, public/**
  datasource:
    url: jdbc:mysql://localhost:3306/belief?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: yao123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: null
#    timeout: 50000ms
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        max-wait: 100000ms
  resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${project.properties.paths-properties.image}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.yaoyili.model

logging:
  file: file/log/pb.log
  level:
    org.springframework.web: DEBUG
    com.yaoyili: DEBUG

##自定义配置

